# Art Basel 2025 Data Preprocessing

This notebook preprocesses the CSV data:
1. Fetches ticket prices from event links using Gemini
2. Standardizes address formats

Run each cell step by step and verify the results before proceeding.

## Setup

In [24]:
# Install required packages (run once)
!pip install google-generativeai pandas python-dotenv pyshorteners

Requirement already satisfied: google-generativeai in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (0.8.5)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: python-dotenv in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (1.0.1)
Collecting pyshorteners
  Downloading pyshorteners-1.0.1.tar.gz (10.0 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: google-ai-generativelanguage==0.6.15 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from google-generativeai) (0.6.15)
Requirement already satisfied: google-api-core in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from google-generativeai) (2.28.1)
Requirement already satisfied: google-api-python-client in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from google-generativeai) (2.187.0)
Requirement already satisfied: google-auth>=2.15.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from google-generativeai) (2.43.0)
Requirement already satisfied: protobuf in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from google-generativeai) (5.29.5)
Requirement already satisfied: pydantic in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from google-generativeai) (2.12.4)
Requirement already satisfied: tqdm in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from google-generativeai) (4.66.5)
Requirement already satisfied: typing-extensions in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from google-generativeai) (4.15.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from google-ai-generativelanguage==0.6.15->google-generativeai) (1.26.1)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from google-api-core->google-generativeai) (1.72.0)
Requirement already satisfied: requests<3.0.0,>=2.18.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from google-api-core->google-generativeai) (2.32.3)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.76.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.71.2)
Requirement already satisfied: cachetools<7.0,>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from google-auth>=2.15.0->google-generativeai) (6.2.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from google-auth>=2.15.0->google-generativeai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from google-auth>=2.15.0->google-generativeai) (4.9.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (2025.10.5)
Requirement already satisfied: pyasn1>=0.1.3 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from rsa<5,>=3.1.4->google-auth>=2.15.0->google-generativeai) (0.6.1)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from google-api-python-client->google-generativeai) (0.31.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from google-api-python-client->google-generativeai) (0.2.1)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from google-api-python-client->google-generativeai) (4.2.0)
Requirement already satisfied: pyparsing<4,>=3.0.4 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client->google-generativeai) (3.2.5)
Requirement already satisfied: annotated-types>=0.6.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pydantic->google-generativeai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pydantic->google-generativeai) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pydantic->google-generativeai) (0.4.2)
Building wheels for collected packages: pyshorteners
  Building wheel for pyshorteners (pyproject.toml) ... done
  Created wheel for pyshorteners: filename=pyshorteners-1.0.1-py3-none-any.whl size=17540 sha256=37fdb8b647f9d27a5334e34d52c1d700c9cd9baa0a58b68c16c0b1337deb38f7
  Stored in directory: /Users/jzamudio/Library/Caches/pip/wheels/30/e9/7c/06d5ea1c320274f44cc35321a75198e266b2d47b3092aa9b7e
Successfully built pyshorteners
Installing collected packages: pyshorteners
Successfully installed pyshorteners-1.0.1

In [46]:
import pandas as pd
import google.generativeai as genai
from dotenv import load_dotenv
import os
import time

# Load environment variables from .env.local (in parent directory)
# Try multiple paths to find the .env.local file
env_paths = [
    '../.env.local',      # If running from scripts folder
    '.env.local',         # If running from project root
    os.path.expanduser('~/.env.local')  # Home directory fallback
]

env_loaded = False
for env_path in env_paths:
    if os.path.exists(env_path):
        load_dotenv(env_path)
        print(f"✓ Loaded environment from: {env_path}")
        env_loaded = True
        break

if not env_loaded:
    print("⚠ No .env.local file found. You can set the API key manually below.")

# Configure Gemini
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')

# If not found, you can set it manually here (uncomment and add your key):
# GEMINI_API_KEY = "your-api-key-here"

if not GEMINI_API_KEY:
    raise ValueError("GEMINI_API_KEY not found. Either:\n1. Create .env.local in the project root with GEMINI_API_KEY=your-key\n2. Uncomment the line above and paste your key directly")

genai.configure(api_key=GEMINI_API_KEY)
model = genai.GenerativeModel('gemini-2.0-flash-lite')

print("✓ Gemini API configured successfully")

✓ Loaded environment from: ../.env.local
✓ Gemini API configured successfully

## Load CSV Data

In [26]:
# Load the CSV
df = pd.read_csv('../art-basel-2025.csv')

print(f"Loaded {len(df)} events")
print(f"\nColumns: {list(df.columns)}")
df.head()

Loaded 172 events

Columns: ['ID', 'Event', 'Event Type', 'Start Date', 'End Date', 'Schedule', 'Neighborhood', 'Address', 'Notes', 'Ticket Price', 'Tickets Link']

,ID,Event,Event Type,Start Date,End Date,Schedule,Neighborhood,Address,Notes,Ticket Price,Tickets Link
0,1,"AI + Web3 $44,000 Pitch Competition & VC Netwo...",Networking,12/5/2025,12/5/2025,10AM - 12PM,NaN,NaN,Location Revealed to Ticket Holders,NaN,https://luma.com/pbs3n297
1,2,24th Iconic Sagamore Brunch,Party,12/6/2025,12/6/2025,9AM - 1PM,Miami Beach,Sagamore Hotel South Beach,NaN,NaN,https://www.eventbrite.com/e/the-24th-iconic-s...
2,3,33+ Hour Space Basel Closing Party,Party,12/7/2025,12/9/2025,NaN,Downtown,"34 NE 11th St, Miami, FL 33132",NaN,NaN,https://dice.fm/event/xenqkk-33-hour-space-bas...
3,4,AfriKin Art Fair,Art Show,12/1/2025,12/7/2025,11AM - 9PM,North Miami,"Maison AfriKin, Scott Galvin Community Center,...",NaN,NaN,https://afrikin.art/
4,5,Alo Wellness Sessions,Wellness,12/4/2025,12/7/2025,10AM - 11AM,Miami Beach,"SCOPE Art Show - 801 Ocean Dr, Miami Beach, FL...",Invite Only,NaN,https://scope-art.com/program

In [27]:
# Check current state of Ticket Price column
print("Ticket Price column stats:")
print(f"  - Empty/NaN: {df['Ticket Price'].isna().sum() + (df['Ticket Price'] == '').sum()}")
print(f"  - Has value: {df['Ticket Price'].notna().sum() - (df['Ticket Price'] == '').sum()}")
print(f"\nSample values:")
df[['Event', 'Ticket Price', 'Tickets Link']].head(10)

Ticket Price column stats:
  - Empty/NaN: 172
  - Has value: 0

Sample values:

,Event,Ticket Price,Tickets Link
0,"AI + Web3 $44,000 Pitch Competition & VC Netwo...",NaN,https://luma.com/pbs3n297
1,24th Iconic Sagamore Brunch,NaN,https://www.eventbrite.com/e/the-24th-iconic-s...
2,33+ Hour Space Basel Closing Party,NaN,https://dice.fm/event/xenqkk-33-hour-space-bas...
3,AfriKin Art Fair,NaN,https://afrikin.art/
4,Alo Wellness Sessions,NaN,https://scope-art.com/program
5,Aqua Art Miami,NaN,https://www.aquaartmiami.com/
6,Aqua Art Miami: VIP Opening,NaN,https://www.aquaartmiami.com
7,Arlo Wynwood: AFTER DARK,NaN,https://www.eventbrite.com/e/art-access-miami-...
8,Arlo Wynwood: Afternoon Art Exhibition,NaN,https://www.eventbrite.com/e/art-access-miami-...
9,Arlo Wynwood: COFFEE + BEATS,NaN,https://www.eventbrite.com/e/art-access-miami-...

## Helper Functions

In [32]:
import requests

def shorten_url_tinyurl(long_url):
    """
    Shortens a given URL using the TinyURL API.

    Args:
        long_url (str): The URL to be shortened.

    Returns:
        str: The shortened TinyURL, or an error message if the request fails.
    """
    api_url = f'http://tinyurl.com/api-create.php?url={long_url}'
    try:
        response = requests.get(api_url)
        response.raise_for_status()  # Raise an exception for bad status codes
        short_url = response.text
        return short_url
    except requests.exceptions.RequestException as e:
        return f"Error shortening URL: {e}"
        
def fetch_ticket_price(event_name, ticket_url, delay=2):
    """
    Use Gemini to estimate ticket price from event info.
    Returns the price string or 'TBD' if unknown.
    """
    if pd.isna(ticket_url) or ticket_url.strip() == '':
        return 'N/A'
    
    prompt = f"""Analyze this event and estimate the starting ticket price.

Event: {event_name}
Ticket URL: {ticket_url}

Based on the URL domain and event name:
- If it's likely free (community events, gallery openings, networking), say "Free"
- If you can estimate a price range, give the starting price like "$25" or "$50+"
- If it's a premium/VIP event, estimate accordingly
- If truly unknown, say "TBD"

Respond with ONLY the price (e.g., "Free", "$25", "$100+", "TBD"). Nothing else."""
    
    try:
        time.sleep(delay)  # Rate limiting
        response = model.generate_content(prompt)
        price = response.text.strip()
        return price
    except Exception as e:
        print(f"  Error: {e}")
        return 'TBD'


def standardize_address(address, neighborhood, delay=2):
    """
    Use Gemini to standardize an address format.
    """
    if pd.isna(address) or address.strip() == '':
        return ''
    
    prompt = f"""Standardize this Miami event address to a consistent format.

Original address: {address}
Neighborhood: {neighborhood if pd.notna(neighborhood) else 'Unknown'}

Format as: "Venue Name, Street Address, City, FL ZIP" (if all info available)
- Keep venue name if present
- Add city/state/zip if missing but inferable from neighborhood
- If it's just a venue name with no street address, search to add the address to the venue name or keep as is
- Clean up any formatting issues

Respond with ONLY the standardized address. Nothing else."""
    
    try:
        time.sleep(delay)  # Rate limiting
        response = model.generate_content(prompt)
        return response.text.strip()
    except Exception as e:
        print(f"  Error: {e}")
        return address  # Return original on error


print("✓ Helper functions defined")

✓ Helper functions defined

## Process Ticket Prices

Process events one by one. You can:
- Run a single event to test
- Run a batch of events
- Skip events that already have prices
- Manually override any result

In [34]:
# Test with a single event first
test_idx = 10  # Change this to test different events

row = df.iloc[test_idx]
short_url = shorten_url(row['Tickets Link'])
print(f"Event: {row['Event']}")
print(f"URL: {short_url}")
print(f"Current Price: {row['Ticket Price']}")
print("\nFetching price...")

price = fetch_ticket_price(row['Event'], row['Tickets Link'])
print(f"Estimated Price: {price}")

Event: Arlo Wynwood: Morning Art Run Club
URL: https://tinyurl.com/2az6szwj
Current Price: nan

Fetching price...
Estimated Price: Free

In [53]:
# Process ticket prices for events that don't have one
# Adjust START_IDX and END_IDX to process in batches

START_IDX = 75   # Start from this row
END_IDX = 175    # Process up to (but not including) this row
DELAY = 10       # Seconds between API calls (increase if hitting rate limits)

for idx in range(START_IDX, min(END_IDX, len(df))):
    row = df.iloc[idx]

    short_url = shorten_url(row['Tickets Link'])
    
    # Skip if already has a price
    current_price = row['Ticket Price']
    if pd.notna(current_price) and str(current_price).strip() != '':
        print(f"[{idx}] {row['Event'][:40]} ({short_url})... SKIP (has: {current_price})")
        continue
    
    print(f"[{idx}] {row['Event'][:40]} ({short_url})...", end=' ')
    
    price = fetch_ticket_price(row['Event'], row['Tickets Link'], delay=DELAY)
    df.at[idx, 'Ticket Price'] = price
    
    print(f"-> {price}")

print("\n✓ Batch complete")

[75] IKEA Open House Miami: Private Event (https://tinyurl.com/27zmyz4t)... SKIP (has: TBD)
[76] IKEA Open House Miami: Public Event (Error: 'float' object has no attribute 'startswith')... SKIP (has: N/A)
[77] Immersive Adventure: Basel Edition  (https://tinyurl.com/22r3fvlx)... SKIP (has: $50+)
[78] Ink Miami Art Fair (https://tinyurl.com/2y73ryvt)... SKIP (has: TBD)
[79] Ink Miami Art Fair (https://tinyurl.com/2y73ryvt)... SKIP (has: TBD)
[80] Ink Miami Art Fair (https://tinyurl.com/2y73ryvt)... SKIP (has: TBD)
[81] Ink Miami Art Fair (https://tinyurl.com/2y73ryvt)... SKIP (has: TBD)
[82] John Summit (https://tinyurl.com/2xzqx7np)... SKIP (has: TBD)
[83] Joia Beach (https://tinyurl.com/25yg2u3a)... -> TBD
[84] Little River Studios (https://tinyurl.com/29tq8llh)... -> TBD
[85] LIV (https://tinyurl.com/2bmhd6vv)... -> $100+
[86] Long Feng Art Car: Blond:ish, Desiree, A (Error: HTTPConnectionPool(host='tinyurl.com', port=80): Read timed out. (read timeout=2))... -> $50+
[87] Long Feng Art Car: Gordo x Mahmut Orhan, (https://tinyurl.com/29t2on2a)... -> $30+
[88] Marshmello (https://tinyurl.com/22k8yxlf)... -> $50+
[89] Maxim Party (Error: 'float' object has no attribute 'startswith')... -> N/A
[90] Medium Cool (Error: 'float' object has no attribute 'startswith')... -> N/A
[91] Miami Art Week  (https://tinyurl.com/2dk7wtux)... -> TBD
[92] Miami Beach Bandshell (https://tinyurl.com/22qwrub3)... -> TBD
[93] Miami Beach Edition Hotel (https://tinyurl.com/23aulha8)... -> TBD
[94] Miami Concours: Cars & Coffee Art Week E (https://tinyurl.com/23nbu6ga)... -> TBD
[95] Miami Design District (https://tinyurl.com/2yjve4ka)... -> Free
[96] Miami Vibes After Party by Paper Buddha  (https://tinyurl.com/23g3oghk)... -> TBD
[97] Mila Lounge (https://tinyurl.com/2ckn5xgn)... -> TBD
[98] MOOON.PARTY Vol*3 (https://tinyurl.com/2yh5fk45)... -> TBD
[99] NADA Miami Art Fair (https://tinyurl.com/25v82x9c)... -> TBD
[100] NADA Miami Art Fair (https://tinyurl.com/25v82x9c)... -> TBD
[101] NADA Miami Art Fair (https://tinyurl.com/25v82x9c)... -> TBD
[102] NADA Miami Art Fair (https://tinyurl.com/25v82x9c)... -> TBD
[103] NFT.MIAMI with Superchief (Error: HTTPConnectionPool(host='tinyurl.com', port=80): Read timed out. (read timeout=2))... -> TBD
[104] No Vacancy Miami Beach (Error: HTTPConnectionPool(host='tinyurl.com', port=80): Read timed out. (read timeout=2))... -> TBD
[105] Nylon Party (Error: 'float' object has no attribute 'startswith')... -> N/A
[106] One Love Miami Art Week (https://tinyurl.com/237cgdoo)... -> TBD
[107] Opening Reception Night at Cadillac Hote (https://tinyurl.com/2d2p24to)... -> TBD
[108] Palm Tree Club (https://tinyurl.com/28ctfa6j)... -> TBD
[109] photoMIAMI (Error: HTTPConnectionPool(host='tinyurl.com', port=80): Read timed out. (read timeout=2))... -> TBD
[110] Pinta Miami (https://tinyurl.com/27wcrgra)... -> TBD
[111] Private Meet & Greet with Faena Artist:  (https://tinyurl.com/297z2ogn)... -> TBD
[112] Prizm (https://tinyurl.com/2ad6r9fj)... -> TBD
[113] Pucci Coffee Lab Pop-Up  (https://tinyurl.com/2aseyg4q)... -> TBD
[114] Rampa (https://tinyurl.com/26mqscw5)... -> $50+
[115] Rampa (https://tinyurl.com/2a9t66cr)... -> $50+
[116] Red Dot (https://tinyurl.com/ygyz84lu)... -> $25+
[117] Red Dot Miami (https://tinyurl.com/ygyz84lu)... -> TBD
[118] Red Dot Miami: Opening Night Preview (https://tinyurl.com/ygyz84lu)... -> TBD
[119] Red Dot Miami: VIP & Press Preview (https://tinyurl.com/ygyz84lu)... -> $100+
[120] Robot Fight Club: Yacht Edition (https://tinyurl.com/22gd4vdk)... -> TBD
[121] SAKAZUKI Experience: Miami (https://tinyurl.com/27jsuax5)... -> TBD
[122] Satellite Art Fair (https://tinyurl.com/2a2arva9)... -> TBD
[123] Satellite Art Fair (https://tinyurl.com/2a2arva9)... -> TBD
[124] Satellite Art Fair (https://tinyurl.com/2a2arva9)... -> TBD
[125] Scope Miami Beach: Concert (https://tinyurl.com/2xjd7mjj)... -> TBD
[126] Scope Miami Beach (https://tinyurl.com/2xjd7mjj)... -> TBD
[127] Scope Miami Beach: Opening Night (https://tinyurl.com/2xjd7mjj)... -> TBD
[128] Scope Miami Beach: VIP & Press Preview (https://tinyurl.com/2xjd7mjj)... -> TBD
[129] Scope Party (https://tinyurl.com/2xjd7mjj)... -> TBD
[130] Sea & Space Summit (https://tinyurl.com/25spgakr)... -> TBD
[131] Senza Fine Concert (Error: 'float' object has no attribute 'startswith')... -> N/A
[132] Slawn X Andrew Miami  (https://tinyurl.com/2a338r3d)... -> TBD
[133] Soho House (Error: 'float' object has no attribute 'startswith')... -> N/A
[134] Solomun (https://tinyurl.com/2757yz2r)... -> TBD
[135] Solomun (https://tinyurl.com/26evztgh)... -> TBD
[136] Spectrum Miami (https://tinyurl.com/2cdv3r3a)... -> $30
[137] Spectrum Miami (https://tinyurl.com/2cdv3r3a)... -> $30
[138] Spectrum Miami: Opening Night (https://tinyurl.com/2cdv3r3a)... -> TBD
[139] Spectrum Miami: VIP & Press Preview (https://tinyurl.com/2cdv3r3a)... -> TBD
[140] Stellar House Miami (https://tinyurl.com/2cx5l7uo)... -> TBD
[141] Strawberry Moon (https://tinyurl.com/2y3gaeov)... -> TBD
[142] Tala Beach (Error: HTTPConnectionPool(host='tinyurl.com', port=80): Read timed out. (read timeout=2))... -> TBD
[143] Tehmplo: WhoMadeWho, Maxi Meraki, Deer J (https://tinyurl.com/25qywy2x)... -> $25
[144] Tehmplo: Tulum (Error: HTTPConnectionPool(host='tinyurl.com', port=80): Read timed out. (read timeout=2))... -> TBD
[145] The $25 Art Show: Closing Day Show (https://tinyurl.com/2donsvhr)... -> $25
[146] The $25 Art Show: Day Show  (https://tinyurl.com/2donsvhr)... -> $25
[147] The Brave New Earth @ Ritz-Carlton (https://tinyurl.com/2b5ojl9a)... -> $100+
[148] The Coffee Party (https://tinyurl.com/2xncvaj4)... -> TBD
[149] The Ethereal Runway Show + Live Art + Li (https://tinyurl.com/2cpx9ddr)... -> TBD
[150] The King*s Exhibition (https://tinyurl.com/2cpee8ga)... -> TBD
[151] The Official Miami Art Week Kickoff Part (Error: 'float' object has no attribute 'startswith')... -> N/A
[152] The Queens* Gathering (https://tinyurl.com/29cxcl85)... -> TBD
[153] The Wellness Oasis by Chase Bank (https://tinyurl.com/22z59dos)... -> Free
[154] Tiesto (https://tinyurl.com/22nz4qxq)... -> $50+
[155] Tiesto (Error: HTTPConnectionPool(host='tinyurl.com', port=80): Read timed out. (read timeout=2))... -> $50+
[156] Toe Jam Backlot Parties (https://tinyurl.com/2a9r6hux)... -> TBD
[157] Untitled Art Miami Beach (Error: HTTPConnectionPool(host='tinyurl.com', port=80): Read timed out. (read timeout=2))... -> TBD
[158] Untitled Art Miami Beach: VIP & Press Pr (https://tinyurl.com/yyap5onh)... -> TBD
[159] Victim 15: After Party (https://tinyurl.com/29haeue5)... -> TBD
[160] Victim 15: Fashion Show (https://tinyurl.com/2bohympv)... -> TBD
[161] Wellness Retreat with The Ethereal (https://tinyurl.com/25cfxqtc)... -> TBD
[162] Wellness Wonderland at Faena  (https://tinyurl.com/2aq7aj9z)... -> TBD
[163] Wondering How is 2025 (https://tinyurl.com/24y2qp36)... -> TBD
[164] Yatch Party: 10 Years of Miki Beach & Bu (https://tinyurl.com/2d9okbpt)... -> $75+
[165] YogArt X Ahana Sunday Service  (https://tinyurl.com/279oy2ae)... -> TBD
[166] ZeyZey (https://tinyurl.com/2dplcjtc)... -> TBD
[167] Barre for Brunch Basel Reset  (https://tinyurl.com/246u4xe9)... -> $25
[168] Art Basel Miami 2025 with LADYDAYDAO (https://tinyurl.com/29rhpdy7)... -> TBD
[169] VNTR Basel Open Community Event  (https://tinyurl.com/2b256gm5)... -> TBD
[170] Tech Basel Miami Mixer (Error: HTTPConnectionPool(host='tinyurl.com', port=80): Read timed out. (read timeout=2))... -> TBD
[171] Deer Jade: The Coffee Grand Opening (https://tinyurl.com/26sfl9aa)... -> TBD

✓ Batch complete

In [52]:
# View current state of ticket prices
df[['Event', 'Ticket Price', 'Tickets Link']].head(85)

,Event,Ticket Price,Tickets Link
0,"AI + Web3 $44,000 Pitch Competition & VC Netwo...",$50+,https://luma.com/pbs3n297
1,24th Iconic Sagamore Brunch,$175,https://www.eventbrite.com/e/the-24th-iconic-s...
2,33+ Hour Space Basel Closing Party,$50+,https://dice.fm/event/xenqkk-33-hour-space-bas...
3,AfriKin Art Fair,$25,https://afrikin.art/
4,Alo Wellness Sessions,$100+,https://scope-art.com/program
...,...,...,...
80,Ink Miami Art Fair,TBD,https://www.inkartfair.com/
81,Ink Miami Art Fair,TBD,https://www.inkartfair.com/
82,John Summit,TBD,https://posh.vip/e/basel-edition-john-summit-p...
83,Joia Beach,NaN,https://dice.fm/partner/tickets/event/q28d79-s...
84,Little River Studios,NaN,https://dice.fm/event/avgexq-unkommon-art-week...

In [ ]:
# Manually fix a specific row's ticket price
# ROW_IDX = 5
# df.at[ROW_IDX, 'Ticket Price'] = 'Free'
# print(f"Updated row {ROW_IDX}: {df.iloc[ROW_IDX]['Event']} -> {df.iloc[ROW_IDX]['Ticket Price']}")

## Process Addresses

Standardize address formats one by one or in batches.

In [54]:
# View current addresses
df[['Event', 'Neighborhood', 'Address']].head(20)

,Event,Neighborhood,Address
0,"AI + Web3 $44,000 Pitch Competition & VC Netwo...",NaN,NaN
1,24th Iconic Sagamore Brunch,Miami Beach,Sagamore Hotel South Beach
2,33+ Hour Space Basel Closing Party,Downtown,"34 NE 11th St, Miami, FL 33132"
3,AfriKin Art Fair,North Miami,"Maison AfriKin, Scott Galvin Community Center,..."
4,Alo Wellness Sessions,Miami Beach,"SCOPE Art Show - 801 Ocean Dr, Miami Beach, FL..."
5,Aqua Art Miami,Miami Beach,"Aqua Art Miami at the Aqua Hotel, 1530 Collins..."
6,Aqua Art Miami: VIP Opening,Miami Beach,"Aqua Art Miami at the Aqua Hotel, 1530 Collins..."
7,Arlo Wynwood: AFTER DARK,Wynwood,"2217 Northwest Miami Court, Miami, FL 33127"
8,Arlo Wynwood: Afternoon Art Exhibition,Wynwood,"2217 Northwest Miami Court, Miami, FL 33127"
9,Arlo Wynwood: COFFEE + BEATS,Wynwood,"2217 Northwest Miami Court, Miami, FL 33127"
10,Arlo Wynwood: Morning Art Run Club,Wynwood,"2217 Northwest Miami Court, Miami, FL 33127"
11,Arlo Wynwood: Yoga & Wellness Circuit,Wynwood,"2217 Northwest Miami Court, Miami, FL 33127"
12,Arodes & Guests,Wynwood,"150 NW 21st St, Miami, FL 33127"
13,Art & Fintech Forum,Miami Beach,Sagamore Hotel South Beach - An All Suite Hote...
14,Art Basel Miami Beach,Miami Beach,Miami Beach Convention Center - 1901 Conventio...
15,Art Basel Miami Beach: Private Days,Miami Beach,Miami Beach Convention Center - 1901 Conventio...
16,Art Basel Miami Beach: Private Days,Miami Beach,Miami Beach Convention Center - 1901 Conventio...
17,Art Basil,Wynwood,FunDimension Game Center
18,Art Exhibition In The Riveria at Cadillac Hote...,Miami Beach,"Cadillac Hotel & Beach Club, 3925 Collins Ave,..."
19,Art Loves Fashion: Sunset Closing Party,Miami Beach,"Pamplemousse on the Bay, 910 West Ave, Miami B..."

In [55]:
# Test with a single address first
test_idx = 1  # Change this to test different events

row = df.iloc[test_idx]
print(f"Event: {row['Event']}")
print(f"Neighborhood: {row['Neighborhood']}")
print(f"Current Address: {row['Address']}")
print("\nStandardizing...")

new_address = standardize_address(row['Address'], row['Neighborhood'])
print(f"Standardized: {new_address}")

Event: 24th Iconic Sagamore Brunch
Neighborhood: Miami Beach
Current Address: Sagamore Hotel South Beach

Standardizing...
Standardized: Sagamore Hotel South Beach, 1671 Collins Ave, Miami Beach, FL 33139

In [56]:
# Process addresses in batches
# Adjust START_IDX and END_IDX to process in batches

START_IDX = 0   # Start from this row
END_IDX = 172    # Process up to (but not including) this row
DELAY = 10       # Seconds between API calls

for idx in range(START_IDX, min(END_IDX, len(df))):
    row = df.iloc[idx]
    
    # Skip if no address
    if pd.isna(row['Address']) or row['Address'].strip() == '':
        print(f"[{idx}] {row['Event'][:40]}... SKIP (no address)")
        continue
    
    print(f"[{idx}] {row['Event'][:40]}...")
    print(f"    Before: {row['Address']}")
    
    new_address = standardize_address(row['Address'], row['Neighborhood'], delay=DELAY)
    df.at[idx, 'Address'] = new_address
    
    print(f"    After:  {new_address}")

print("\n✓ Batch complete")

[0] AI + Web3 $44,000 Pitch Competition & VC... SKIP (no address)
[1] 24th Iconic Sagamore Brunch...
    Before: Sagamore Hotel South Beach
    After:  Sagamore Hotel South Beach, 1671 Collins Ave, Miami Beach, FL 33139
[2] 33+ Hour Space Basel Closing Party...
    Before: 34 NE 11th St, Miami, FL 33132
    After:  34 NE 11th St, Miami, FL 33132
[3] AfriKin Art Fair...
    Before: Maison AfriKin, Scott Galvin Community Center, 1600 NE 126th Street, North Miami, FL 33181
    After:  Maison AfriKin, Scott Galvin Community Center, 1600 NE 126th Street, North Miami, FL 33181
[4] Alo Wellness Sessions...
    Before: SCOPE Art Show - 801 Ocean Dr, Miami Beach, FL 33139
    After:  SCOPE Art Show, 801 Ocean Dr, Miami Beach, FL 33139
[5] Aqua Art Miami...
    Before: Aqua Art Miami at the Aqua Hotel, 1530 Collins Avenue, Miami Beach, FL 33139
    After:  Aqua Art Miami at the Aqua Hotel, 1530 Collins Avenue, Miami Beach, FL 33139
[6] Aqua Art Miami: VIP Opening...
    Before: Aqua Art Miami at the Aqua Hotel, 1530 Collins Avenue, Miami Beach, FL 33139
    After:  Aqua Art Miami at the Aqua Hotel, 1530 Collins Avenue, Miami Beach, FL 33139
[7] Arlo Wynwood: AFTER DARK...
    Before: 2217 Northwest Miami Court, Miami, FL 33127
    After:  2217 NW Miami Court, Miami, FL 33127
[8] Arlo Wynwood: Afternoon Art Exhibition...
    Before: 2217 Northwest Miami Court, Miami, FL 33127
    After:  2217 Northwest Miami Court, Miami, FL 33127
[9] Arlo Wynwood: COFFEE + BEATS...
    Before: 2217 Northwest Miami Court, Miami, FL 33127
    After:  2217 NW Miami Court, Miami, FL 33127
[10] Arlo Wynwood: Morning Art Run Club...
    Before: 2217 Northwest Miami Court, Miami, FL 33127
    After:  2217 NW Miami Court, Miami, FL 33127
[11] Arlo Wynwood: Yoga & Wellness Circuit...
    Before: 2217 Northwest Miami Court, Miami, FL 33127
    After:  2217 NW Miami Court, Miami, FL 33127
[12] Arodes & Guests ...
    Before: 150 NW 21st St, Miami, FL 33127
    After:  150 NW 21st St, Miami, FL 33127
[13] Art & Fintech Forum...
    Before: Sagamore Hotel South Beach - An All Suite Hotel, The Sagamore, 1671 Collins Ave, Miami Beach, FL 33139, USA
    After:  Sagamore Hotel South Beach, 1671 Collins Ave, Miami Beach, FL 33139
[14] Art Basel Miami Beach...
    Before: Miami Beach Convention Center - 1901 Convention Center Drive, FL 33139
    After:  Miami Beach Convention Center, 1901 Convention Center Drive, Miami Beach, FL 33139
[15] Art Basel Miami Beach: Private Days...
    Before: Miami Beach Convention Center - 1901 Convention Center Drive, FL 33139
    After:  Miami Beach Convention Center, 1901 Convention Center Drive, Miami Beach, FL 33139
[16] Art Basel Miami Beach: Private Days...
    Before: Miami Beach Convention Center - 1901 Convention Center Drive, FL 33139
    After:  Miami Beach Convention Center, 1901 Convention Center Drive, Miami Beach, FL 33139
[17] Art Basil...
    Before: FunDimension Game Center
    After:  FunDimension Game Center, 298 NE 61st St, Miami, FL 33137
[18] Art Exhibition In The Riveria at Cadilla...
    Before: Cadillac Hotel & Beach Club, 3925 Collins Ave, Miami Beach, FL, 33140. Cadillac Hotel Website
    After:  Cadillac Hotel & Beach Club, 3925 Collins Ave, Miami Beach, FL 33140
[19] Art Loves Fashion: Sunset Closing Party...
    Before: Pamplemousse on the Bay, 910 West Ave, Miami Beach, FL 33139
    After:  Pamplemousse on the Bay, 910 West Ave, Miami Beach, FL 33139
[20] Art Miami ...
    Before: The Art Miami Pavilion, One Herald Plaza, NE 14th Street & Biscayne Bay, Miami, FL 33132
    After:  The Art Miami Pavilion, One Herald Plaza, Miami, FL 33132
[21] Art Padel Miami ... SKIP (no address)
[22] Art Week at Tala Beach...
    Before: 2341 Collins Avenue, Miami Beach, FL 33139
    After:  2341 Collins Avenue, Miami Beach, FL 33139
[23] Art With Me...
    Before: Green Space at Mana Wynwood - 318 NW 23rd St, Miami, FL 33127
    After:  Green Space at Mana Wynwood, 318 NW 23rd St, Miami, FL 33127
[24] Arte NXT Pop-Up Show...
    Before: The Miami Art Week Gallery, 2300 N. Miami Avenue, Miami FL 33127
    After:  The Miami Art Week Gallery, 2300 N Miami Ave, Miami, FL 33127
[25] Arte NXT Pop-Up Show...
    Before: The Miami Art Week Gallery, 2300 N. Miami Avenue, Miami FL 33127
    After:  The Miami Art Week Gallery, 2300 N Miami Ave, Miami, FL 33127
[26] Bagattelle Miami River... SKIP (no address)
[27] Basel City...
    Before: Sagamore Hotel South Beach
    After:  Sagamore Hotel South Beach, 1671 Collins Ave, Miami Beach, FL 33139
[28] BitBasel...
    Before: The Sagamore Hotel - 1671 Collins Ave, Miami Beach, FL 33139
    After:  The Sagamore Hotel, 1671 Collins Ave, Miami Beach, FL 33139
[29] BitBasel: VIP Opening Ceremony...
    Before: Sagamore Hotel South Beach
    After:  Sagamore Hotel South Beach, 1671 Collins Ave, Miami Beach, FL 33139
[30] BitBasel: Basel City...
    Before: The Sagamore, 1671 Collins Ave, Miami Beach, FL 33139
    After:  The Sagamore, 1671 Collins Ave, Miami Beach, FL 33139
[31] Black Book Records: Chris Lake, Chris Lo... SKIP (no address)
[32] BLACK COFFEE...
    Before: 73 West Flagler Street
    After:  73 W Flagler St, Miami, FL 33130
[33] Blondish...
    Before: 150 NW 21st St, Miami, FL 33127
    After:  150 NW 21st St, Miami, FL 33127
[34] Boho House... SKIP (no address)
[35] Brave New World Art Exhibit and Fashion ...
    Before: Ritz Carlton South Beach
    After:  The Ritz-Carlton South Beach, 1 Lincoln Rd, Miami Beach, FL 33139
[36] Brave New World Art Exhibit and Fashion ...
    Before: Ritz Carlton South Beach
    After:  The Ritz-Carlton South Beach, 1 Lincoln Rd, Miami Beach, FL 33139
[37] Broken Shaker: How a Sunset Sounds...
    Before: 2727 Indian Creek Dr #11, Miami Beach, FL 33140
    After:  2727 Indian Creek Dr #11, Miami Beach, FL 33140
[38] CapitalOne Party...
    Before: 1111 Lincoln Road
    After:  1111 Lincoln Road, Miami Beach, FL 33139
[39] Casa Neos...
    Before: 40 SW North River Dr, Miami, FL 33128
    After:  40 SW North River Dr, Miami, FL 33128
[40] Chase Sapphire Concerts ... SKIP (no address)
[41] Chase Sappire Experience Art Show... SKIP (no address)
[42] Chromasthesia...
    Before: The Gates Hotel South Beach 2360 Collins Ave, Miami Beach, FL 33139, USA
    After:  The Gates Hotel South Beach, 2360 Collins Ave, Miami Beach, FL 33139
[43] Circoloco...
    Before: 4800 NW 37th Ave, Miami, FL 33142
    After:  4800 NW 37th Ave, Miami, FL 33142
[44] Club M2...
    Before: 1235 Washington Ave, Miami Beach, FL 33139
    After:  1235 Washington Ave, Miami Beach, FL 33139
[45] Club Space...
    Before: 34 NE 11th St, Miami, FL 33132
    After:  34 NE 11th St, Miami, FL 33132
[46] Context Art Miami...
    Before: The CONTEXT Art Miami Pavilion, One Herald Plaza, NE 14th Street & Biscayne Bay, Miami, FL 33132
    After:  CONTEXT Art Miami Pavilion, One Herald Plaza, Miami, FL 33132
[47] Context Art Miami: VIP Preview...
    Before: The CONTEXT Art Miami Pavilion, One Herald Plaza, NE 14th Street & Biscayne Bay, Miami, FL 33132
    After:  CONTEXT Art Miami Pavilion, One Herald Plaza, Miami, FL 33132
[48] CryptoMondays MIA & FLL Field Trip at th...
    Before: 1205 Washington Avenue
    After:  1205 Washington Avenue, Miami Beach, FL 33139
[49] DAER... SKIP (no address)
[50] Dante's Hifi... SKIP (no address)
[51] Design Miami...
    Before: Convention Center Drive & 19th Street, Miami Beach
    After:  Convention Center Drive & 19th Street, Miami Beach, FL 33139
[52] Design Miami: Collectors Preview...
    Before: Convention Center Drive & 19th Street, Miami Beach
    After:  Convention Center Drive & 19th Street, Miami Beach, FL, 33139
[53] Design Miami: Members Preview...
    Before: Convention Center Drive & 19th Street, Miami Beach
    After:  Convention Center Drive & 19th Street, Miami Beach, FL, 33139
[54] Diplo...
    Before: 29 NE 11th St, Miami, 33132
    After:  29 NE 11th St, Miami, FL 33132
[55] Disclosure DJ Set + Carlita...
    Before: 1819 79th Street Causeway North Bay Village, FL 33141
    After:  1819 79th Street Causeway, North Bay Village, FL 33141
[56] Distraction Party: Jay Weinberg, Deli Gi... SKIP (no address)
[57] Do Not Sit On The Furniture...
    Before: 423 16th St, Miami Beach, Florida 33139
    After:  423 16th St, Miami Beach, FL 33139
[58] Driven by Art: Live Car Sculpture by Hir...
    Before: Cadillac Hotel & Beach Club, 3925 Collins Ave, Miami Beach, FL, 33140. Cadillac Hotel Website
    After:  Cadillac Hotel & Beach Club, 3925 Collins Ave, Miami Beach, FL 33140
[59] E11even...
    Before: 29 NE 11th St, Miami, 33132
    After:  29 NE 11th St, Miami, FL 33132
[60] Eden Gallery...
    Before: The Setai - 2001 Collins Ave, Miami Beach, FL 33139
    After:  The Setai, 2001 Collins Ave, Miami Beach, FL 33139
[61] Factory Town...
    Before: 4800 NW 37th Ave, Miami, FL 33142
    After:  4800 NW 37th Ave, Miami, FL 33142
[62] Faena Art...
    Before: 3201 Collins Ave, Miami Beach, FL 33140
    After:  3201 Collins Ave, Miami Beach, FL 33140
[63] Faena Music Series...
    Before: 3201 Collins Ave, Miami Beach, FL 33140
    After:  3201 Collins Ave, Miami Beach, FL 33140
[64] Ferrari Party... SKIP (no address)
[65] Flower Party: Art Basel Edition...
    Before: Novotel Rooftop (Brickell) 1500 SW 1st Ave, Miami, FL 33129
    After:  Novotel Rooftop (Brickell), 1500 SW 1st Ave, Miami, FL 33129
[66] Francis Mercier...
    Before: 34 NE 11th St, Miami, FL 33132
    After:  34 NE 11th St, Miami, FL 33132
[67] Freakquencies: Lydia Lunch & Tim Dahl, L... SKIP (no address)
[68] Frequency: Basel Edition...
    Before: Electric 23 (144 NW 23rd St, Miami, FL 33127)
    After:  Electric 23, 144 NW 23rd St, Miami, FL 33127
[69] Gordo...
    Before: 150 NW 21st St, Miami, FL 33127
    After:  150 NW 21st St, Miami, FL 33127
[70] Green Velvet B2B Joseph Capriati...
    Before: 150 NW 21st St, Miami, FL 33127
    After:  150 NW 21st St, Miami, FL 33127
[71] HarryPotterObamaSonic10inU...
    Before: South Pointe Tavern, 40 South Pointe Dr #109, Miami Beach, FL 33139
    After:  South Pointe Tavern, 40 South Pointe Dr #109, Miami Beach, FL 33139
[72] Hive Wynwood...
    Before: The Wynwood Marketplace - 2250 NW 2nd Ave, Miami, FL 33127
    After:  The Wynwood Marketplace, 2250 NW 2nd Ave, Miami, FL 33127
[73] Hugel...
    Before: 4800 NW 37th Ave, Miami, FL 33142
    After:  4800 NW 37th Ave, Miami, FL 33142
[74] Hugel...
    Before: 300 Northeast 71st Street, Miami, Florida 33138
    After:  300 NE 71st Street, Miami, FL 33138
[75] IKEA Open House Miami: Private Event...
    Before: 1108 Lincoln Road
    After:  1108 Lincoln Road, Miami Beach, FL 33139
[76] IKEA Open House Miami: Public Event...
    Before: 1108 Lincoln Road
    After:  1108 Lincoln Road, Miami Beach, FL 33139
[77] Immersive Adventure: Basel Edition ...
    Before: M2 Miami Beach 1235 Washington Ave, Miami Beach, FL 33139
    After:  M2 Miami Beach, 1235 Washington Ave, Miami Beach, FL 33139
[78] Ink Miami Art Fair...
    Before: Suites of Dorchester, 1850 Collins Ave., Miami Beach, FL 33139
    After:  Suites of Dorchester, 1850 Collins Ave, Miami Beach, FL 33139
[79] Ink Miami Art Fair...
    Before: Suites of Dorchester, 1850 Collins Ave., Miami Beach, FL 33139
    After:  Suites of Dorchester, 1850 Collins Ave, Miami Beach, FL 33139
[80] Ink Miami Art Fair...
    Before: Suites of Dorchester, 1850 Collins Ave., Miami Beach, FL 33139
    After:  Suites of Dorchester, 1850 Collins Ave, Miami Beach, FL 33139
[81] Ink Miami Art Fair...
    Before: Suites of Dorchester, 1850 Collins Ave., Miami Beach, FL 33139
    After:  Suites of Dorchester, 1850 Collins Ave, Miami Beach, FL 33139
[82] John Summit...
    Before: 1819 79th Street Causeway North Bay Village, FL 33141
    After:  1819 79th Street Causeway, North Bay Village, FL 33141
[83] Joia Beach...
    Before: 1111 Parrot Jungle Trail, Miami, Florida 33132
    After:  Parrot Jungle Trail, 1111 Parrot Jungle Trail, Miami, FL 33132
[84] Little River Studios...
    Before: 300 Northeast 71st Street, Miami, Florida 33138
    After:  300 Northeast 71st Street, Miami, FL 33138
[85] LIV...
    Before: Fontainebleau Miami Beach - 4441 Collins Avenue, Miami Beach, FL 33140
    After:  Fontainebleau Miami Beach, 4441 Collins Avenue, Miami Beach, FL 33140
[86] Long Feng Art Car: Blond:ish, Desiree, A...
    Before: 150 NW 21st Miami,FL 33127
    After:  150 NW 21st St, Miami, FL 33127
[87] Long Feng Art Car: Gordo x Mahmut Orhan,...
    Before: 150 NW 21st Miami,FL 33127
    After:  150 NW 21st St, Miami, FL 33127
[88] Marshmello...
    Before: 29 NE 11th St, Miami, 33132
    After:  29 NE 11th St, Miami, FL 33132
[89] Maxim Party... SKIP (no address)
[90] Medium Cool... SKIP (no address)
[91] Miami Art Week ...
    Before: Miami Art Week Wynwood Gallery - 2300 N Miami Ave, Miami, FL 33127, USA
    After:  Miami Art Week Wynwood Gallery, 2300 N Miami Ave, Miami, FL 33127
[92] Miami Beach Bandshell...
    Before: 7275 Collins Avenue, Miami Beach FL. 33141
    After:  7275 Collins Avenue, Miami Beach, FL 33141
[93] Miami Beach Edition Hotel...
    Before: 2901 Collins Ave, Miami Beach, FL 33140
    After:  2901 Collins Ave, Miami Beach, FL 33140
[94] Miami Concours: Cars & Coffee Art Week E...
    Before: 40 NE 40th St, Miami, FL 33137
    After:  40 NE 40th St, Miami, FL 33137
[95] Miami Design District... SKIP (no address)
[96] Miami Vibes After Party by Paper Buddha ...
    Before: Gates Hotel Rooftop, 2360 Collins Ave, Miami Beach, FL 33139
    After:  Gates Hotel Rooftop, 2360 Collins Ave, Miami Beach, FL 33139
[97] Mila Lounge...
    Before: 1636 Meridian Ave, Miami Beach, FL 33139
    After:  1636 Meridian Ave, Miami Beach, FL 33139
[98] MOOON.PARTY Vol*3...
    Before: Sagamore Hotel South Beach
    After:  Sagamore Hotel South Beach, 1671 Collins Ave, Miami Beach, FL 33139
[99] NADA Miami Art Fair...
    Before: NADA Miami - 1400 N Miami Ave, Miami, FL 33136
    After:  NADA Miami, 1400 N Miami Ave, Miami, FL 33136
[100] NADA Miami Art Fair...
    Before: Ice Palace Studios, 1400 North Miami Avenue, Miami, FL 33136
    After:  Ice Palace Studios, 1400 North Miami Avenue, Miami, FL 33136
[101] NADA Miami Art Fair...
    Before: Ice Palace Studios, 1400 North Miami Avenue, Miami, FL 33136
    After:  Ice Palace Studios, 1400 North Miami Avenue, Miami, FL 33136
[102] NADA Miami Art Fair...
    Before: Ice Palace Studios, 1400 North Miami Avenue, Miami, FL 33136
    After:  Ice Palace Studios, 1400 North Miami Avenue, Miami, FL 33136
[103] NFT.MIAMI with Superchief...
    Before: Sagamore Hotel South Beach
    After:  Sagamore Hotel South Beach, 1671 Collins Ave, Miami Beach, FL 33139
[104] No Vacancy Miami Beach... SKIP (no address)
[105] Nylon Party... SKIP (no address)
[106] One Love Miami Art Week...
    Before: The Gates Hotel South Beach 2360 Collins Ave, Miami Beach, FL 33139, USA
    After:  The Gates Hotel South Beach, 2360 Collins Ave, Miami Beach, FL 33139
[107] Opening Reception Night at Cadillac Hote...
    Before: Cadillac Hotel & Beach Club, 3925 Collins Ave, Miami Beach, FL, 33140. Cadillac Hotel Website
    After:  Cadillac Hotel & Beach Club, 3925 Collins Ave, Miami Beach, FL 33140
[108] Palm Tree Club...
    Before: 1819 79th Street Causeway North Bay Village, FL 33141
    After:  1819 79th Street Causeway, North Bay Village, FL 33141
[109] photoMIAMI...
    Before: The Miami Art Week Gallery, 2300 N. Miami Avenue, Miami FL 33127
    After:  The Miami Art Week Gallery, 2300 N Miami Ave, Miami, FL 33127
[110] Pinta Miami...
    Before: The Hangar - 3385 Pan American Drive, Coconut Grove, Fl
    After:  The Hangar, 3385 Pan American Drive, Coconut Grove, FL 33133
[111] Private Meet & Greet with Faena Artist: ...
    Before: 3201 Collins Ave, Miami Beach, FL 33140
    After:  3201 Collins Ave, Miami Beach, FL 33140
[112] Prizm...
    Before: Dec 3-4 TBA / Dec 5 Soho Pool House
    After:  Soho Pool House, Miami Beach, FL 33139
[113] Pucci Coffee Lab Pop-Up ...
    Before: Pucci - 140 NE 39th St Suite 102, Miami FL, 33137
    After:  Pucci, 140 NE 39th St Suite 102, Miami, FL 33137
[114] Rampa...
    Before: 300 Northeast 71st Street, Miami, Florida 33138
    After:  300 NE 71st Street, Miami, FL 33138
[115] Rampa...
    Before: 1819 79th Street Causeway North Bay Village, FL 33141
    After:  1819 79th Street Causeway, North Bay Village, FL 33141
[116] Red Dot...
    Before: Mana Wynwood - 2217 NW 5th Avenue, Miami, FL 33127
    After:  Mana Wynwood, 2217 NW 5th Avenue, Miami, FL 33127
[117] Red Dot Miami...
    Before: Mana Wynwood, 2217 NW 5th Avenue, NW 22nd St, Miami, FL 33127
    After:  Mana Wynwood, 2217 NW 5th Avenue, Miami, FL 33127
[118] Red Dot Miami: Opening Night Preview...
    Before: Mana Wynwood, 2217 NW 5th Avenue, NW 22nd St, Miami, FL 33127
    After:  Mana Wynwood, 2217 NW 5th Avenue, Miami, FL 33127
[119] Red Dot Miami: VIP & Press Preview...
    Before: Mana Wynwood, 2217 NW 5th Avenue, NW 22nd St, Miami, FL 33127
    After:  Mana Wynwood, 2217 NW 5th Avenue, Miami, FL 33127
[120] Robot Fight Club: Yacht Edition...
    Before: Seafair Mega Yacht, South Dock, Chopin Plaza, Miami, FL 33131, United States
    After:  Seafair Mega Yacht, South Dock, Chopin Plaza, Miami, FL 33131
[121] SAKAZUKI Experience: Miami...
    Before: Hiyakawa Miami, 2700 N Miami Ave #5, Miami, FL 33127
    After:  Hiyakawa Miami, 2700 N Miami Ave #5, Miami, FL 33127
[122] Satellite Art Fair...
    Before: Collins Avenue (Satellite Hotel)
    After:  Satellite Hotel, Collins Avenue, Miami Beach, FL
[123] Satellite Art Fair...
    Before: Collins Avenue (Satellite Hotel)
    After:  Satellite Hotel, Collins Avenue, Miami Beach, FL
[124] Satellite Art Fair...
    Before: Collins Avenue (Satellite Hotel)
    After:  Collins Avenue, Miami Beach, FL
[125] Scope Miami Beach: Concert...
    Before: SCOPE Art Show - 801 Ocean Dr, Miami Beach, FL 33139
    After:  SCOPE Art Show, 801 Ocean Dr, Miami Beach, FL 33139
[126] Scope Miami Beach...
    Before: 801 Ocean Drive, Miami Beach, FL 33139 (between 8th & 10th Street)
    After:  801 Ocean Drive, Miami Beach, FL 33139
[127] Scope Miami Beach: Opening Night...
    Before: 801 Ocean Drive, Miami Beach, FL 33139 (between 8th & 10th Street)
    After:  801 Ocean Drive, Miami Beach, FL 33139
[128] Scope Miami Beach: VIP & Press Preview...
    Before: 801 Ocean Drive, Miami Beach, FL 33139 (between 8th & 10th Street)
    After:  801 Ocean Drive, Miami Beach, FL 33139
[129] Scope Party...
    Before: SCOPE Art Show - 801 Ocean Dr, Miami Beach, FL 33139
    After:  SCOPE Art Show, 801 Ocean Dr, Miami Beach, FL 33139
[130] Sea & Space Summit...
    Before: Sagamore Hotel South Beach
    After:  Sagamore Hotel South Beach, 1671 Collins Ave, Miami Beach, FL 33139
[131] Senza Fine Concert... SKIP (no address)
[132] Slawn X Andrew Miami ...
    Before: Andrew - 54 NE 40th St, Miami, Fl 33137
    After:  Andrew, 54 NE 40th St, Miami, FL 33137
[133] Soho House...
    Before: 4385 Collins Ave, Miami Beach, FL 33140
    After:  4385 Collins Ave, Miami Beach, FL 33140
[134] Solomun...
    Before: 34 NE 11th St, Miami, FL 33132
    After:  34 NE 11th St, Miami, FL 33132
[135] Solomun...
    Before: 4800 NW 37th Ave, Miami, FL 33142
    After:  4800 NW 37th Ave, Miami, FL 33142
[136] Spectrum Miami...
    Before: Mana Wynwood, 2217 NW 5th Avenue, NW 22nd St, Miami, FL 33127
    After:  Mana Wynwood, 2217 NW 5th Avenue, Miami, FL 33127
[137] Spectrum Miami...
    Before: Mana Wynwood, 2217 NW 5th Avenue, NW 22nd St, Miami, FL 33127
    After:  Mana Wynwood, 2217 NW 5th Avenue, Miami, FL 33127
[138] Spectrum Miami: Opening Night...
    Before: Mana Wynwood, 2217 NW 5th Avenue, NW 22nd St, Miami, FL 33127
    After:  Mana Wynwood, 2217 NW 5th Avenue, Miami, FL 33127
[139] Spectrum Miami: VIP & Press Preview...
    Before: Mana Wynwood, 2217 NW 5th Avenue, NW 22nd St, Miami, FL 33127
    After:  Mana Wynwood, 2217 NW 5th Avenue, Miami, FL 33127
[140] Stellar House Miami...

In [ ]:
# Manually fix a specific row's address
# ROW_IDX = 5
# df.at[ROW_IDX, 'Address'] = '123 Main St, Miami, FL 33101'
# print(f"Updated row {ROW_IDX}")

## Review & Save

In [57]:
# Review all changes
print("Final data preview:")
df[['Event', 'Ticket Price', 'Address']].head(30)

Final data preview:

,Event,Ticket Price,Address
0,"AI + Web3 $44,000 Pitch Competition & VC Netwo...",$50+,NaN
1,24th Iconic Sagamore Brunch,$175,"Sagamore Hotel South Beach, 1671 Collins Ave, ..."
2,33+ Hour Space Basel Closing Party,$50+,"34 NE 11th St, Miami, FL 33132"
3,AfriKin Art Fair,$25,"Maison AfriKin, Scott Galvin Community Center,..."
4,Alo Wellness Sessions,$100+,"SCOPE Art Show, 801 Ocean Dr, Miami Beach, FL ..."
5,Aqua Art Miami,$25,"Aqua Art Miami at the Aqua Hotel, 1530 Collins..."
6,Aqua Art Miami: VIP Opening,$100+,"Aqua Art Miami at the Aqua Hotel, 1530 Collins..."
7,Arlo Wynwood: AFTER DARK,$50+,"2217 NW Miami Court, Miami, FL 33127"
8,Arlo Wynwood: Afternoon Art Exhibition,Free,"2217 Northwest Miami Court, Miami, FL 33127"
9,Arlo Wynwood: COFFEE + BEATS,Free,"2217 NW Miami Court, Miami, FL 33127"
10,Arlo Wynwood: Morning Art Run Club,Free,"2217 NW Miami Court, Miami, FL 33127"
11,Arlo Wynwood: Yoga & Wellness Circuit,$25,"2217 NW Miami Court, Miami, FL 33127"
12,Arodes & Guests,$25,"150 NW 21st St, Miami, FL 33127"
13,Art & Fintech Forum,$50+,"Sagamore Hotel South Beach, 1671 Collins Ave, ..."
14,Art Basel Miami Beach,$73,"Miami Beach Convention Center, 1901 Convention..."
15,Art Basel Miami Beach: Private Days,$73,"Miami Beach Convention Center, 1901 Convention..."
16,Art Basel Miami Beach: Private Days,$50+,"Miami Beach Convention Center, 1901 Convention..."
17,Art Basil,$25,"FunDimension Game Center, 298 NE 61st St, Miam..."
18,Art Exhibition In The Riveria at Cadillac Hote...,$100+,"Cadillac Hotel & Beach Club, 3925 Collins Ave,..."
19,Art Loves Fashion: Sunset Closing Party,$25,"Pamplemousse on the Bay, 910 West Ave, Miami B..."
20,Art Miami,$50+,"The Art Miami Pavilion, One Herald Plaza, Miam..."
21,Art Padel Miami,$75,NaN
22,Art Week at Tala Beach,$50+,"2341 Collins Avenue, Miami Beach, FL 33139"
23,Art With Me,$100+,"Green Space at Mana Wynwood, 318 NW 23rd St, M..."
24,Arte NXT Pop-Up Show,$25,"The Miami Art Week Gallery, 2300 N Miami Ave, ..."
25,Arte NXT Pop-Up Show,$25,"The Miami Art Week Gallery, 2300 N Miami Ave, ..."
26,Bagattelle Miami River,N/A,NaN
27,Basel City,$50+,"Sagamore Hotel South Beach, 1671 Collins Ave, ..."
28,BitBasel,$50+,"The Sagamore Hotel, 1671 Collins Ave, Miami Be..."
29,BitBasel: VIP Opening Ceremony,$100+,"Sagamore Hotel South Beach, 1671 Collins Ave, ..."

In [63]:
# Check for any remaining empty ticket prices
empty_prices = df[df['Ticket Price'].isna() | (df['Ticket Price'] == '')]
print(f"Events still missing ticket prices: {len(empty_prices)}")
if len(empty_prices) > 0:
    print(empty_prices[['Event', 'Tickets Link']])

Events still missing ticket prices: 0

In [61]:
# Save the preprocessed CSV
output_path = '../art-basel-2025.csv'
df.to_csv(output_path, index=False)
print(f"✓ Saved to {output_path}")
print(f"\nNext step: Run 'npm run update-data' to convert to JSON")

✓ Saved to art-basel-2025-preprocessed.csv

Next step: Run 'npm run update-data' to convert to JSON

In [65]:
# Optional: Overwrite the original CSV instead
# df.to_csv('../art-basel-2025.csv', index=False)
# print("✓ Saved to art-basel-2025.csv (original overwritten)")

✓ Saved to art-basel-2025.csv (original overwritten)